const inputToIconMap = {
  f: "/icons/forward.webp",
  n: "/icons/neutral.webp",
  df: "/icons/down-forward.webp",
  d: "/icons/down.webp",
  db: "/icons/down-back.webp",
  b: "/icons/back.webp",
  ub: "/icons/up-back.webp",
  u: "/icons/up.webp",
  uf: "/icons/up-forward.webp",
  1: "/icons/1.webp",
  2: "/icons/2.webp",
  3: "/icons/3.webp",
  4: "/icons/4.webp",
  "1+2": "/icons/1+2.webp",
  "1+3": "/icons/1+3.webp",
  "1+4": "/icons/1+4.webp",
  "2+3": "/icons/2+3.webp",
  "2+4": "/icons/2+4.webp",
  "3+4": "/icons/3+4.webp",
  "1+2+3": "/icons/1+2+3.webp",
  "1+2+4": "/icons/1+2+4.webp",
  "1+3+4": "/icons/1+3+4.webp",
  "2+3+4": "/icons/2+3+4.webp",
  "1+2+3+4": "/icons/1+2+3+4.webp",
  hqcf: "/icons/half-quarter-circle-forward.webp",
  hqcb: "/icons/half-quarter-circle-back.webp",
  qcf: "/icons/quarter-circle-forward.webp",
  qcb: "/icons/quarter-circle-back.webp",
  hcf: "/icons/half-circle-back.webp",
  hcb: "/icons/half-circle-back.webp",
  holdF: "/icons/hold-forward.webp",
  holdB: "/icons/hold-back.webp",
  holdD: "/icons/hold-down.webp",
  holdU: "/icons/hold-up.webp",
  holdDF: "/icons/hold-down-forward.webp",
  holdDB: "/icons/hold-down-back.webp",
  holdUF: "/icons/hold-up-forward.webp",
  holdUB: "/icons/hold-up-back.webp",
};

export default inputToIconMap;
