const inputToIconMap = {
  f: "/icons/f.webp",
  n: "/icons/n.webp",
  df: "/icons/df.webp",
  d: "/icons/d.webp",
  db: "/icons/db.webp",
  b: "/icons/b.webp",
  ub: "/icons/ub.webp",
  u: "/icons/u.webp",
  uf: "/icons/uf.webp",
  1: "/icons/1.webp",
  2: "/icons/2.webp",
  3: "/icons/3.webp",
  4: "/icons/4.webp",
  "1+2": "/icons/1+2.webp",
  "1+3": "/icons/1+3.webp",
  "1+4": "/icons/1+4.webp",
  "2+3": "/icons/2+3.webp",
  "2+4": "/icons/2+4.webp",
  "3+4": "/icons/3+4.webp",
  "1+2+3": "/icons/1+2+3.webp",
  "1+2+4": "/icons/1+2+4.webp",
  "1+3+4": "/icons/1+3+4.webp",
  "2+3+4": "/icons/2+3+4.webp",
  "1+2+3+4": "/icons/1+2+3+4.webp",
  holdf: "/icons/holdf.webp",
  holdb: "/icons/holdb.webp",
  holdd: "/icons/holdd.webp",
  holdu: "/icons/holdu.webp",
  holddf: "/icons/holddf.webp",
  holddb: "/icons/holddb.webp",
  holduf: "/icons/holduf.webp",
  holdub: "/icons/holdub.webp",
};

export default inputToIconMap;
